### ISSUE TITLE
2784题目数据是有问题吧。。

### ISSUE THREAD

**Issue by wood3** [lazzzis/PutongOJ#1]
PAT一样的代码过了 但是在这边就出问题了。。是自己出的数据吗？能不能看看数据？

**Comment by lazzzis** [comment]
@wood3 数据确实和 PAT 不一样。你的代码我看过了，有一组测试数据没通过:

```
2
-2/3 -1/3
```

理应输出 -1，你的代码输出 1

**Comment by wood3** [comment]
不好意思啊 的确是我审题不清
以为是说不能整数部分有负号 想象的话 的确不可能整数部分有负号
所以题目那个负号在分子的意思是分母不能有负号对吧？
修改后的代码还是各种wa
然后我这儿学弟说出现了一个问题

oj为什么改不了签名。。。- -
退出登录也退不了

弹出了错误信息
Network error or System Error! Check the Network and then ask the admin for help

**Comment by wood3** [comment]
http://paste.ubuntu.com/25080730/  
顺便贴一个我的代码。。大佬有空的话希望能看看。。。。

**Comment by lazzzis** [comment]
首先，谢谢你 @wood3 的反馈。

1. 因为我看你2784 已经 AC，所以我就不继续评论了

2. 不能修改签名应该是我最近不小心引入的 bug 。。。_:(´□`」 ∠):_

因为服务器只能在校内网才能成功 SSH，而且本项目的部分开发者已经不在学校了，所以我让校内其它人去 fix 了。不过会慢几天。。(✖╭╮✖)

**Comment by wood3** [comment]
好的！

**Comment by lazzzis** [comment]
暂时解决了签名问题和退出登录问题，把 PUT 请求改成了 POST 请求，虽然语义不符

**Comment by wood3** [comment]
辛苦
