### ISSUE TITLE
3205 汉诺塔问题

### ISSUE THREAD

**Issue by wood3** [lazzzis/PutongOJ#3]
样例输出最后一个前面的都是1, 2, 最后一个迷之7.
应该是。。。测试数据错了吧。。
然后有没有考虑在oj上加一个小的讨论板？

**Comment by lazzzis** [comment]
看了后台数据，确实有问题。大概是老师出题目的时候失误了。。。
现在已改正。

讨论版其实在考虑中，近期会实现一个试一下

**Comment by wood3** [comment]
好的！
