### ISSUE TITLE
学校OJ资磁c++11吗？

### ISSUE THREAD

**Issue by zyxhangzhou** [lazzzis/PutongOJ#5]
如题

**Comment by lazzzis** [comment]
"你问我资磁不资磁，我说资磁。"

以下代码可以通过 751，[http://pastebin.ubuntu.com/25370261/](http://pastebin.ubuntu.com/25370261/)。

FAQ 那里写错了，稍后修正

**Comment by zyxhangzhou** [comment]
吼！
